name: Build and Upload Release Artifact

on:
  release:
    types: [created] # Se ejecuta cuando se crea una nueva release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Get project version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifact to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: SDAICore-${{ env.VERSION }}
          path: target/*.jar

      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v4
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
