name: Build and Publish Maven Artifact

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Copy Maven settings
      run: cp .github/maven/settings.xml $HOME/.m2/settings.xml

    - name: Extract Maven version
      id: extract_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install --settings $HOME/.m2/settings.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SDAICore-${{ env.VERSION }}
        path: target/*.jar

    - name: Create GitHub release
      uses: actions/create-release@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        files: target/*.jar
