name: Build and Publish Maven Artifact

on:
  pull_request:
    branches:
      - master
permissions:
    contents: write
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Copy Maven settings
      run: cp .github/maven/settings.xml $HOME/.m2/settings.xml

    - name: Extract Maven version
      id: extract_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install --settings $HOME/.m2/settings.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SDAICore-${{ env.VERSION }}
        path: target/*.jar

    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ env.VERSION }} target/*.jar --title "Release ${{ env.VERSION }}" --notes "Release notes"

